services:
  - type: web
    name: exhibition-backend
    runtime: docker
    rootDir: exhibition-backend

    envVars:
      - key: SERVER_PORT
        value: "8888"

      - key: DB_USER
        fromDatabase:
          name: exhibition-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: exhibition-db
          property: password

      - key: DB_HOST
        fromDatabase:
          name: exhibition-db
          property: host

      - key: DB_PORT
        fromDatabase:
          name: exhibition-db
          property: port

      - key: DB_NAME
        fromDatabase:
          name: exhibition-db
          property: database

      - key: DB_DRIVER
        value: org.postgresql.Driver

      - key: EMAIL_PROVIDER
        value: smtp

      - key: SMTP_HOST
        value: smtp-relay.brevo.com

      - key: SMTP_PORT
        value: "587"

      - key: SMTP_USER
        value: a923b0001@smtp-brevo.com

      - key: SMTP_FROM
        value: dagimawitkelem129@gmail.com

      - key: SMTP_USE_TLS
        value: "true"

      - key: ADMIN_EMAIL
        value: dagimawitkelem129@gmail.com

      - key: ADMIN_PASSWORD
        value: Dagikelem123@

      - key: ALLOWED_ORIGINS
        value: https://exhibition-frontend.onrender.com

  - type: static
    name: exhibition-frontend
    rootDir: exhibition-frontend
    buildCommand: npm install --legacy-peer-deps && npm run build -- --configuration=production
    staticPublishPath: dist/exhibition-frontend/browser

    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: exhibition-db
    databaseName: exhibition_db
    user: exhibition_system